version: "2.3"

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  quarkus-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus-back
    mem_limit: 256m
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://quarkus-db:5432/rest-crud
    ports:
      - "8081:8080"  # the HTTP endpoint
    depends_on:
      quarkus-db:
        condition: service_healthy
    networks:
      - quarkus

  quarkus-db:
    image: "postgres:10.5"
    mem_limit: 256m
    environment:
      - POSTGRES_USER=restcrud
      - POSTGRES_PASSWORD=restcrud
      - POSTGRES_DB=rest-crud
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restcrud -d rest-crud"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    networks:
      - quarkus
volumes:
  data:
networks:
  quarkus:
    driver: bridge